<?php

namespace Jalle19\StatusManager\Console;

use Symfony\Component\Console\Input\InputInterface;

/**
 * Created by PhpStorm.
 * User: negge
 * Date: 2015-08-30
 * Time: 09:39
 */
class SingleCommandApplication extends \Symfony\Component\Console\Application
{

	/**
	 * @var string the name of the command to run
	 */
	private $_commandName;

	/**
	 * @var mixed the command class
	 */
	private $_commandClass;


	public function __construct($commandName, $commandClass, $name = 'UNKNOWN', $version = 'UNKNOWN')
	{
		$this->_commandName  = $commandName;
		$this->_commandClass = $commandClass;

		parent::__construct($name, $version); // TODO: Change the autogenerated stub
	}


	/**
	 * @inheritdoc
	 */
	protected function getCommandName(InputInterface $input)
	{
		return $this->_commandName;
	}


	/**
	 * @inheritdoc
	 */
	protected function getDefaultCommands()
	{
		$defaultCommands   = parent::getDefaultCommands();
		$defaultCommands[] = new $this->_commandClass;

		return $defaultCommands;
	}


	/**
	 * @inheritdoc
	 */
	public function getDefinition()
	{
		$inputDefinition = parent::getDefinition();
		$inputDefinition->setArguments();

		return $inputDefinition;
	}
}
